### ISSUE TITLE
1.5 Crash

### ISSUE THREAD

**Issue by BenHerron** [Jagged/InRam#16]
When running unit test

    Result StackTrace:	
    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
       at lambda_method(Closure , GroupSubscription )
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Jagged.InRam.InRamSet`1.PreloadAllSetsWithRelatedEntities(DbContext dbContext) in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 160
       at Jagged.InRam.InRamSet`1.System.Linq.IQueryable.get_Provider() in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 79
       at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
       at lambda_method(Closure , Group )
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Jagged.InRam.InRamSet`1.PreloadAllSetsWithRelatedEntities(DbContext dbContext) in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 160
       at Jagged.InRam.InRamSet`1.System.Linq.IQueryable.get_Provider() in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 79
       at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
       at lambda_method(Closure , Organisation )
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Jagged.InRam.InRamSet`1.PreloadAllSetsWithRelatedEntities(DbContext dbContext) in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 160
       at Jagged.InRam.InRamSet`1.System.Linq.IQueryable.get_Provider() in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 79
       at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
       at lambda_method(Closure , Feed )
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Jagged.InRam.InRamSet`1.PreloadAllSetsWithRelatedEntities(DbContext dbContext) in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 160
       at Jagged.InRam.InRamSet`1.System.Linq.IQueryable.get_Provider() in C:\Users\Will\Google Drive\Prog - Projects\InRam\src\InRamSet.cs:line 79
       at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
       at Moss.Web.Api.Queries.GetFeedForUser.GetFeedForUserQueryHandler.Handle(GetFeedForUserQuery cmd) in C:\<path>\Queries\GetFeedForUser\GetFeedForUserQueryHandler.cs:line 24
       at Moss.Web.Api.Tests.Queries.GetFeedForUser.GetFeedForUserQueryHandlerTest.WorksWhenEverythingValid() in C:\<path>\Queries\GetFeedForUser\GetFeedForUserQueryHandlerTest.cs:line 137
    Result Message:	
    Test method Moss.Web.Api.Tests.Queries.GetFeedForUser.GetFeedForUserQueryHandlerTest.WorksWhenEverythingValid threw exception: 
    System.InvalidOperationException: Sequence contains more than one element

**Comment by Jagged** [comment]
This could be caused if there are two or more entities related to another which should only have one.

Can you please supply a test case that reproduces this?

**Comment by Jagged** [comment]
Not a bug, Moss unit test was faulty and adding same entity multiple times due to typo.
